/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package todolist;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class ToDoListTela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ToDoListTela.class.getName());

    /**
     * Creates new form ToDoListTela
     */
    public ToDoListTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDescricaoTarefa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarefas = new javax.swing.JTable();
        jButtonAdicionarTarefa = new javax.swing.JButton();
        jButtonConcluirTarefa = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBoxTodos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldDescricaoTarefa.addActionListener(this::jTextFieldDescricaoTarefaActionPerformed);

        jTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tarefas", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTableTarefas);

        jButtonAdicionarTarefa.setText("Adicionar");
        jButtonAdicionarTarefa.addActionListener(this::jButtonAdicionarTarefaActionPerformed);

        jButtonConcluirTarefa.setText("Concluir");
        jButtonConcluirTarefa.addActionListener(this::jButtonConcluirTarefaActionPerformed);

        jButton3.setText("Remover");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jComboBoxTodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Concluidos", "Não concluidos" }));
        jComboBoxTodos.addActionListener(this::jComboBoxTodosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdicionarTarefa)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBoxTodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonConcluirTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescricaoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarTarefa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConcluirTarefa)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarTarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionarTarefaActionPerformed

    private void jComboBoxTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTodosActionPerformed

    private void jTextFieldDescricaoTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoTarefaActionPerformed
    
    }//GEN-LAST:event_jTextFieldDescricaoTarefaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
        int linhaSelecionada = jTableTarefas.getSelectedRow();
        
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Nenhuma tarefa foi selecionada");
            return;
        }
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a tarefa?");
        
        String tarefaSelecionada = recuperarTarefa(linhaSelecionada);
        
        int indiceTarefaSelecionada = tarefas.indexOF(tarefaSelecionada);
        
        if (opcao == JOptionPane.YES_OPTION){
            tarefas.remove(indiceTarefaSelecionada);
            preencherTabela();
            
        }
        
        filtrarTabela();
        
        preencherTabela();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonConcluirTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirTarefaActionPerformed
        int linhaSelecionada = jTableTarefas.getSelectedRow();
        
        if (linhaSelecionada < 0){
            JOptionPane.showMessageDialog(null, "Nenhuma tarefa selecionada");
            return;
        }
        String tarefaSelecionada = recuperarTarefa(linhaSelecionada);
        
        int indiceTarefasSelecionada = tarefas.indexOF(tarefaSelecionada);
        
        String[] dados = tarefas.get(indiceTarefasSelecionada).split(";");
        
        tarefas.set(indiceTarefasSelecionada. dados[0] + ";" + CONCLUIDA);
        
        filtrarTabela();
        preencherTabela();
    }//GEN-LAST:event_jButtonConcluirTarefaActionPerformed
   private void filtrarTabela(){
       int opcao = jComboBoxFiltroStatus.getSelectedIndex();
       tarefasFiltradas.clear();
       
       String[] dados;
       
       for(String tarefa : tarefas){
           dados = tarefa.split(";");
           
           switch (opcao) {
               case 0:
                   tarefasFiltradas.add(tarefa);
                   
                   break;
               case 1:
                   if (dados[1].equals(CONCLUIDO)){
                       tarefasFiltradas.add(tarefa);
                   }
                   break;
               default:
                   throw new AssertionError();
           }
           
           
       }
   }
    private String recuperarTarefa(int indiceTarefa){
        
        if (jComboFiltroStatus.getSelectedIndex() > 0){
            tarefaFiltradas.get(IndiceTarefa);
                  
        }else{
            
            
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ToDoListTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdicionarTarefa;
    private javax.swing.JButton jButtonConcluirTarefa;
    private javax.swing.JComboBox<String> jComboBoxTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTarefas;
    private javax.swing.JTextField jTextFieldDescricaoTarefa;
    // End of variables declaration//GEN-END:variables
}
